// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hvumawxgspmovexblofn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh2dW1hd3hnc3Btb3ZleGJsb2ZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxMzg1NDUsImV4cCI6MjA3MjcxNDU0NX0.2mKMlOJJY3SmYx2CORu4a_g6uiBUp3ObjaiV3Vvbfus";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});